# Generated by Django 5.1.6 on 2025-03-17 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='departments',
            fields=[
                ('deptID', models.IntegerField(primary_key=True, serialize=False)),
                ('deptName', models.CharField(max_length=100)),
                ('college', models.CharField(choices=[('COCIS', 'College of Computing and Information Sciences'), ('CEDAT', 'College of Engineering, Design, Art and Technology')], max_length=10)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='roles',
            fields=[
                ('role', models.CharField(choices=[('S', 'Student'), ('L', 'Lecturer'), ('A', 'Admin')], max_length=1)),
                ('roleID', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='issues',
            fields=[
                ('issueID', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('MM', 'Missing Marks'), ('MC', 'Missing Coursework'), ('WM', 'Wrong Marks'), ('MP', 'Paper Missed')], max_length=2)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('CREATED', 'CREATED'), ('PENDING', 'PENDING'), ('OPEN', 'OPEN'), ('RESOLVED', 'RESOLVED'), ('CLOSED', 'CLOSED')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.CharField(max_length=100)),
                ('deptID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aits_api.departments')),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('userID', models.IntegerField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=100)),
                ('firstName', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('roleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aits_api.roles')),
            ],
        ),
        migrations.CreateModel(
            name='notifications',
            fields=[
                ('notID', models.IntegerField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('READ', 'READ'), ('UNREAD', 'UNREAD')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issueID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aits_api.issues')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aits_api.users')),
            ],
        ),
        migrations.AddField(
            model_name='issues',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aits_api.users'),
        ),
    ]
