# Generated by Django 5.1.6 on 2025-03-17 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aits_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='role',
            field=models.CharField(choices=[('S', 'Student'), ('L', 'Lecturer'), ('A', 'Admin'), ('R', 'Registrar')], max_length=1),
        ),
    ]
