# Generated by Django 5.1.7 on 2025-03-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aits_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='college',
            field=models.CharField(choices=[('COCIS', 'College of Computing and Information Sciences'), ('CEDAT', 'College of Engineering, Design, Art and Technology'), ('COBAMS', 'College of Business and Management Sciences'), ('CHUSS', 'College of Humanities and Social Sciences')], max_length=10),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('PENDING', 'PENDING'), ('OPEN', 'OPEN'), ('RESOLVED', 'RESOLVED')], default='CREATED', max_length=20),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
