# Generated by Django 5.1.6 on 2025-03-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aits_api', '0007_alter_issues_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issues',
            name='issue',
        ),
        migrations.AlterField(
            model_name='issues',
            name='category',
            field=models.CharField(choices=[('MM', 'Missing Marks'), ('MC', 'Missing Coursework'), ('WM', 'Wrong Marks'), ('MP', 'Paper Missed')], max_length=2),
        ),
        migrations.AlterField(
            model_name='issues',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='issues',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('In Progress', 'In Progress'), ('RESOLVED', 'RESOLVED'), ('CLOSED', 'CLOSED')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='message',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='roles',
            name='role',
            field=models.CharField(choices=[('S', 'Student'), ('L', 'Lecturer'), ('A', 'Administrator')], max_length=1),
        ),
    ]
